# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='object_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='actor_object_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_object_id',
            field=models.BigIntegerField(db_index=True, blank=True, null=True, ),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_object_object_id',
            field=models.BigIntegerField(db_index=True, blank=True, null=True,),
        ),
    ]
